title: matt_wyz
author:
  name: Matthew W.
  email: matthew@mattwyz.xyz
  
description:
  (c) matthew w. 2023-2024
  No part of this site shall be reproduced in any way, shape or form.
  
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  
logo: /favicon.png

header_pages:
  - index.md
  - about.md
  - projects.md

minima:
  skin: auto

  minima:
  social_links:
    - { platform: instagram, user_url: "https://instagram.com/matt_wyz" }
    - { platform: twitter, user_url: "https://twitter.com/matt_wyz" }
    - { platform: youtube, user_url: "https://youtube.com/@matt_wyz" }
